/**
 * Field table, group `graph` (12 definitions).
 *
 * Transcribed once from `SCHEMAS.md` §1 `$defs` (l1-freeze.2, schemaVersion 1.1.0).
 * Do not hand-edit: `test/protocol/schema-drift.test.ts` re-parses the frozen document and
 * fails on any divergence in the definition set, property set, required set or field type.
 */
import type { DefsSchema } from '../defs.js';

export const GRAPH_DEFS = {
  "TaskContract": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "protocol": {"$ref":"#/$defs/ProtocolVersion","description":"协议封套","x-source":"CONTRACTS §1","x-mapping":"K"},
      "taskId": {"$ref":"#/$defs/Id","description":"用户任务 id","x-source":"CONTRACTS §1","x-mapping":"K"},
      "version": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"任务修订","x-source":"CONTRACTS §1","x-mapping":"K"},
      "goal": {"type":"string","minLength":1,"description":"用户目标","x-source":"CONTRACTS §1","x-mapping":"K"},
      "requiredOutcomes": {"type":"array","items":{"$ref":"#/$defs/OutcomeRequirement"},"minItems":1,"uniqueItems":true,"description":"必须达到的结果","x-source":"CONTRACTS §1","x-mapping":"K"},
      "requiredBranches": {"type":"array","items":{"$ref":"#/$defs/Id"},"minItems":0,"uniqueItems":true,"description":"明确必须分支，允许单 agent 空集合","x-source":"CONTRACTS §1","x-mapping":"K"},
      "acceptance": {"$ref":"#/$defs/AcceptancePolicy","description":"唯一 task 验收合同","x-source":"CONTRACTS §1","x-mapping":"K"},
      "scope": {"$ref":"#/$defs/Scope","description":"workspace/artifact 范围","x-source":"CONTRACTS §1","x-mapping":"K"},
      "authorityGrant": {"$ref":"#/$defs/Grant","description":"显式权限子集","x-source":"CONTRACTS §1","x-mapping":"K"},
      "budget": {"$ref":"#/$defs/BudgetPolicy","description":"父/子共享预算","x-source":"CONTRACTS §1","x-mapping":"K"},
      "privacy": {"$ref":"#/$defs/PrivacyPolicy","description":"反馈与数据边界","x-source":"CONTRACTS §1","x-mapping":"K"},
      "termination": {"$ref":"#/$defs/TerminationPolicy","description":"尝试/取消/时间边界","x-source":"CONTRACTS §1","x-mapping":"K"},
      "requiredGuarantees": {"type":"array","items":{"$ref":"#/$defs/GuaranteeRequirement"},"minItems":1,"uniqueItems":true,"description":"准入要求","x-source":"CONTRACTS §1","x-mapping":"K"},
      "degradations": {"type":"array","items":{"$ref":"#/$defs/DegradationOption"},"minItems":0,"uniqueItems":true,"description":"显式替代，禁止隐式弱化","x-source":"CONTRACTS §1","x-mapping":"K"},
    },
    "required": ["protocol","taskId","version","goal","requiredOutcomes","requiredBranches","acceptance","scope","authorityGrant","budget","privacy","termination","requiredGuarantees","degradations"],
  },
  "GraphSpec": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "protocol": {"$ref":"#/$defs/ProtocolVersion","description":"协议封套","x-source":"CONTRACTS §1","x-mapping":"K"},
      "graphId": {"$ref":"#/$defs/Id","description":"产品图，独立于 SP","x-source":"CONTRACTS §1","x-mapping":"K"},
      "revision": {"type":"integer","minimum":0,"maximum":9007199254740991,"description":"图修订","x-source":"CONTRACTS §1","x-mapping":"K"},
      "taskContractRef": {"$ref":"#/$defs/ContractRef","description":"确切任务合同","x-source":"CONTRACTS §1","x-mapping":"K"},
      "nodes": {"type":"array","items":{"$ref":"#/$defs/NodeSpec"},"minItems":1,"uniqueItems":true,"description":"允许单 agent，禁止强制拆分","x-source":"CONTRACTS §1","x-mapping":"K"},
      "typedEdges": {"type":"array","items":{"$ref":"#/$defs/EdgeSpec"},"minItems":0,"uniqueItems":true,"description":"类型边集合","x-source":"CONTRACTS §1","x-mapping":"K"},
      "requiredJoins": {"type":"array","items":{"$ref":"#/$defs/Id"},"minItems":0,"uniqueItems":true,"description":"所有 join node ids","x-source":"CONTRACTS §1","x-mapping":"K"},
      "resourcePolicy": {"type":"array","items":{"$ref":"#/$defs/ResourcePolicy"},"minItems":0,"uniqueItems":true,"description":"图级命名资源策略","x-source":"CONTRACTS §1","x-mapping":"K"},
      "graphLimits": {"$ref":"#/$defs/GraphLimits","description":"明确边界","x-source":"CONTRACTS §1","x-mapping":"K"},
      "abandonedBranches": {"type":"array","items":{"$ref":"#/$defs/AbandonedBranch"},"minItems":0,"uniqueItems":true,"description":"保留证据，仅经 patch 写入","x-source":"CONTRACTS §1","x-mapping":"K"},
    },
    "required": ["protocol","graphId","revision","taskContractRef","nodes","typedEdges","requiredJoins","resourcePolicy","graphLimits","abandonedBranches"],
  },
  "NodeSpec": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "nodeId": {"$ref":"#/$defs/Id","description":"运行节点 id","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "kind": {"type":"string","enum":["agent","tool","deterministic","evaluate","join","human","subgraph"],"description":"七类节点","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "inputRefs": {"type":"array","items":{"$ref":"#/$defs/ArtifactRef"},"minItems":0,"uniqueItems":true,"description":"本 attempt 消费输入","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "outputSchemas": {"type":"array","items":{"$ref":"#/$defs/SchemaRef"},"minItems":0,"uniqueItems":true,"description":"输出约束","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "loop": {"anyOf":[{"$ref":"#/$defs/LoopSpec"},{"type":"null"}],"description":"显式有界 loop","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "subgraph": {"anyOf":[{"$ref":"#/$defs/GraphRef"},{"type":"null"}],"description":"被委派子图","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "contextPlan": {"$ref":"#/$defs/ContextPlan","description":"有限上下文","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "toolRequirements": {"type":"array","items":{"$ref":"#/$defs/GuaranteeRequirement"},"minItems":0,"uniqueItems":true,"description":"原生工具能力","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"TOOL"},
      "modelRequirements": {"$ref":"#/$defs/ModelRequirement","description":"模型条件","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "resources": {"$ref":"#/$defs/Resources","description":"资源声明而非边；CONTRACTS §1 的 read/write resources 在本版按 SEMANTICS §3.2 表达为 exclusive/shared（Scope 仍保留 readResources/writeResources）","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "termination": {"$ref":"#/$defs/TerminationPolicy","description":"停止边界","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "terminal": {"type":"boolean","description":"显式终局标记，无 real consumer 必须 true","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
      "requiredBranches": {"type":"array","items":{"$ref":"#/$defs/Id"},"minItems":0,"uniqueItems":true,"description":"join 的明确 fan-in，非 join 必须空","x-source":"CONTRACTS §1; graph SEMANTICS §2/§4","x-mapping":"K"},
    },
    "required": ["nodeId","kind","inputRefs","outputSchemas","loop","subgraph","contextPlan","toolRequirements","modelRequirements","resources","termination","terminal","requiredBranches"],
  },
  "GraphPatch": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "protocol": {"$ref":"#/$defs/ProtocolVersion","description":"协议封套","x-source":"graph SEMANTICS §5","x-mapping":"K"},
      "graphId": {"$ref":"#/$defs/Id","description":"目标图","x-source":"graph SEMANTICS §5","x-mapping":"K"},
      "expectedRevision": {"type":"integer","minimum":0,"maximum":9007199254740991,"description":"拓扑 CAS","x-source":"graph SEMANTICS §5","x-mapping":"K"},
      "adds": {"type":"array","items":{"$ref":"#/$defs/NodeSpec"},"minItems":0,"uniqueItems":true,"description":"新增节点","x-source":"graph SEMANTICS §5","x-mapping":"K"},
      "changes": {"type":"array","items":{"$ref":"#/$defs/NodeSpec"},"minItems":0,"uniqueItems":true,"description":"替换完整未认领 NodeSpec","x-source":"graph SEMANTICS §5","x-mapping":"K"},
      "removals": {"type":"array","items":{"$ref":"#/$defs/Id"},"minItems":0,"uniqueItems":true,"description":"仅无证据、未认领节点","x-source":"graph SEMANTICS §5","x-mapping":"K"},
      "typedEdges": {"type":"array","items":{"$ref":"#/$defs/EdgeSpec"},"minItems":0,"uniqueItems":true,"description":"显式完整新边集，无隐式猜测","x-source":"graph SEMANTICS §5","x-mapping":"K"},
      "abandonedBranches": {"type":"array","items":{"$ref":"#/$defs/AbandonedBranch"},"minItems":0,"uniqueItems":true,"description":"累计放弃标注","x-source":"graph SEMANTICS §5","x-mapping":"K"},
      "reason": {"type":"string","minLength":1,"description":"变更理由","x-source":"graph SEMANTICS §5","x-mapping":"K"},
      "authorityRef": {"$ref":"#/$defs/Id","description":"不得提升权限","x-source":"graph SEMANTICS §5","x-mapping":"K"},
    },
    "required": ["protocol","graphId","expectedRevision","adds","changes","removals","typedEdges","abandonedBranches","reason","authorityRef"],
  },
  "EdgeSpec": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "edgeId": {"$ref":"#/$defs/Id","description":"边身份","x-source":"graph SEMANTICS §3","x-mapping":"K"},
      "type": {"type":"string","enum":["dependency","data","route","repair","fallback","provenance"],"description":"六类边，不含 resource/join","x-source":"graph SEMANTICS §3","x-mapping":"K"},
      "from": {"$ref":"#/$defs/Id","description":"上游/生产者","x-source":"graph SEMANTICS §3","x-mapping":"K"},
      "to": {"$ref":"#/$defs/Id","description":"下游/消费者","x-source":"graph SEMANTICS §3","x-mapping":"K"},
      "when": {"anyOf":[{"$ref":"#/$defs/Predicate"},{"type":"null"}],"description":"routing 条件，非 routing 为 null","x-source":"graph SEMANTICS §3","x-mapping":"K"},
      "artifact": {"anyOf":[{"$ref":"#/$defs/ArtifactRef"},{"type":"null"}],"description":"data 的实际输入绑定","x-source":"graph SEMANTICS §3","x-mapping":"K"},
      "expect": {"anyOf":[{"$ref":"#/$defs/SchemaRef"},{"type":"null"}],"description":"data 消费 schema","x-source":"graph SEMANTICS §3","x-mapping":"K"},
      "maxAttempts": {"anyOf":[{"$ref":"#/$defs/PositiveCount"},{"type":"null"}],"description":"repair/fallback 累计 attempt 界","x-source":"graph SEMANTICS §3","x-mapping":"K"},
      "relation": {"anyOf":[{"$ref":"#/$defs/Id"},{"type":"null"}],"description":"provenance 关系，不参与 ready","x-source":"graph SEMANTICS §3","x-mapping":"K"},
    },
    "required": ["edgeId","type","from","to","when","artifact","expect","maxAttempts","relation"],
  },
  "Predicate": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "op": {"type":"string","enum":["eq","neq","all","any","not","true"],"description":"纯数据谓词 AST；禁止 eval/代码字符串","x-source":"graph SEMANTICS §3.0/§3.1","x-mapping":"K"},
      "path": {"anyOf":[{"$ref":"#/$defs/Id"},{"type":"null"}],"description":"outcome/reason/env 中显式路径；复合谓词为 null","x-source":"graph SEMANTICS §3.0/§3.1","x-mapping":"K"},
      "value": {"anyOf":[{"type":"string"},{"type":"boolean"},{"type":"integer","minimum":-9007199254740991,"maximum":9007199254740991},{"type":"null"}],"description":"eq/neq 比较JSON标量；复合谓词为null","x-source":"graph SEMANTICS §3.0/§3.1; 冻结提案","x-mapping":"K"},
      "children": {"type":"array","items":{"$ref":"#/$defs/Predicate"},"minItems":0,"uniqueItems":true,"description":"复合操作子谓词；原子谓词空","x-source":"graph SEMANTICS §3.0/§3.1","x-mapping":"K"},
    },
    "required": ["op","path","value","children"],
  },
  "LoopSpec": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "bodyNodeIds": {"type":"array","items":{"$ref":"#/$defs/Id"},"minItems":1,"uniqueItems":true,"description":"显式 loop body","x-source":"graph SEMANTICS §4","x-mapping":"K"},
      "maxIterations": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"迭代上限（§4 的 `bound{...}` 包装在本版拍平为顶层字段）","x-source":"graph SEMANTICS §4","x-mapping":"K"},
      "maxWallClock": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"loop 累计活跃毫秒（同上）","x-source":"graph SEMANTICS §4","x-mapping":"K"},
      "maxTokensOrCost": {"$ref":"#/$defs/BudgetBound","description":"累计 token/USD 界（同上）","x-source":"graph SEMANTICS §4","x-mapping":"K"},
      "maxDepth": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"嵌套深度界（同上）","x-source":"graph SEMANTICS §4","x-mapping":"K"},
      "stop": {"type":"array","items":{"type":"string","enum":["body-success","bound-exhausted","irreparable-failure"]},"minItems":1,"uniqueItems":true,"description":"仅 body-success/bound-exhausted/irreparable-failure","x-source":"graph SEMANTICS §4","x-mapping":"K"},
      "carry": {"type":"array","items":{"$ref":"#/$defs/ArtifactRef"},"minItems":0,"uniqueItems":true,"description":"显式迭代输入增量","x-source":"graph SEMANTICS §4","x-mapping":"K"},
    },
    "required": ["bodyNodeIds","stop","carry"],
    "allOf": [{"anyOf":[{"required":["maxIterations","maxWallClock"]},{"required":["maxIterations","maxTokensOrCost"]},{"required":["maxIterations","maxDepth"]},{"required":["maxWallClock","maxTokensOrCost"]},{"required":["maxWallClock","maxDepth"]},{"required":["maxTokensOrCost","maxDepth"]}]}],
  },
  "GraphLimits": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "maxNodes": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"节点数界","x-source":"graph SEMANTICS §4/§5","x-mapping":"K"},
      "maxConcurrentAgents": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"原生并发会话界","x-source":"graph SEMANTICS §4/§5","x-mapping":"K"},
      "maxDepth": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"loop/subgraph 总深度界","x-source":"graph SEMANTICS §4/§5","x-mapping":"K"},
      "maxAttempts": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"图级累计尝试界","x-source":"graph SEMANTICS §4/§5","x-mapping":"K"},
    },
    "required": ["maxNodes","maxConcurrentAgents","maxDepth","maxAttempts"],
  },
  "ContextPlan": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "inputRefs": {"type":"array","items":{"$ref":"#/$defs/ArtifactRef"},"minItems":0,"uniqueItems":true,"description":"有限输入 packet","x-source":"CONTRACTS §1/§3","x-mapping":"K"},
      "maxTokens": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"上下文注入界","x-source":"CONTRACTS §1/§3","x-mapping":"K"},
      "preserveHostResources": {"const":true,"description":"保留原 instructions/skills/tools","x-source":"CONTRACTS §1/§3","x-mapping":"CONTEXT"},
      "isolation": {"type":"string","enum":["current","fresh"],"description":"当前会话或新 transcript","x-source":"CONTRACTS §1/§3","x-mapping":"CHILD"},
    },
    "required": ["inputRefs","maxTokens","preserveHostResources","isolation"],
  },
  "ModelRequirement": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "providerModel": {"anyOf":[{"$ref":"#/$defs/ModelId"},{"type":"null"}],"description":"真实 provider/model；未选定 null","x-source":"evaluation PROTOCOL §9","x-mapping":"MODEL"},
      "reasoningRequested": {"anyOf":[{"$ref":"#/$defs/Id"},{"type":"null"}],"description":"请求参数标签","x-source":"evaluation PROTOCOL §9","x-mapping":"HIGH"},
      "reasoningGuarantee": {"type":"string","enum":["payload-only","server-tier"],"description":"参数接受不等于独立档位","x-source":"evaluation PROTOCOL §9","x-mapping":"HIGH"},
      "payloadRef": {"anyOf":[{"$ref":"#/$defs/ArtifactRef"},{"type":"null"}],"description":"宿主内三臂 thinking payload 内容摘要","x-source":"evaluation PROTOCOL §9","x-mapping":"HIGH"},
    },
    "required": ["providerModel","reasoningRequested","reasoningGuarantee","payloadRef"],
  },
  "AbandonedBranch": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "nodeId": {"$ref":"#/$defs/Id","description":"被明确放弃分支","x-source":"graph SEMANTICS §2.4","x-mapping":"K"},
      "authorityRef": {"$ref":"#/$defs/Id","description":"有权放弃的 grant","x-source":"graph SEMANTICS §2.4","x-mapping":"K"},
      "reason": {"type":"string","minLength":1,"description":"可审计理由","x-source":"graph SEMANTICS §2.4","x-mapping":"K"},
      "at": {"$ref":"#/$defs/Instant","description":"注入 Clock 记录，非排序依据","x-source":"graph SEMANTICS §2.4","x-mapping":"K"},
    },
    "required": ["nodeId","authorityRef","reason","at"],
  },
  "NodeStateEntry": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "nodeId": {"$ref":"#/$defs/Id","description":"节点 id","x-source":"CONTRACTS §4; graph SEMANTICS §2.2","x-mapping":"K"},
      "attemptOrdinal": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"该状态所属 attempt 序号","x-source":"CONTRACTS §4; graph SEMANTICS §2.3","x-mapping":"K"},
      "epoch": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"判定该状态时的 session epoch","x-source":"CONTRACTS §4/§5; graph SEMANTICS §2.3","x-mapping":"K"},
      "state": {"$ref":"#/$defs/NodeState","description":"节点当前状态；不是完成声明","x-source":"CONTRACTS §4; graph SEMANTICS §2.2","x-mapping":"K"},
      "sinceSequence": {"$ref":"#/$defs/Count","description":"进入该状态的 journal sequence","x-source":"CONTRACTS §4/§5","x-mapping":"ORDER"},
    },
    "required": ["nodeId","attemptOrdinal","epoch","state","sinceSequence"],
  },
} as const satisfies DefsSchema;
