/**
 * Field table, group `runtime` (11 definitions).
 *
 * Transcribed once from `SCHEMAS.md` §1 `$defs` (l1-freeze.2, schemaVersion 1.1.0).
 * Do not hand-edit: `test/protocol/schema-drift.test.ts` re-parses the frozen document and
 * fails on any divergence in the definition set, property set, required set or field type.
 */
import type { DefsSchema } from '../defs.js';

export const RUNTIME_DEFS = {
  "Command": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "protocol": {"$ref":"#/$defs/ProtocolVersion","description":"封套","x-source":"CONTRACTS §1","x-mapping":"K"},
      "commandId": {"$ref":"#/$defs/Id","description":"幂等身份，同 id 不同内容拒绝","x-source":"CONTRACTS §1","x-mapping":"K"},
      "sessionId": {"$ref":"#/$defs/Id","description":"目标内核 session","x-source":"CONTRACTS §1","x-mapping":"SESSION"},
      "expectedRevision": {"type":"integer","minimum":0,"maximum":9007199254740991,"description":"journal revision CAS，与 graph revision 分离","x-source":"CONTRACTS §1","x-mapping":"K"},
      "actor": {"$ref":"#/$defs/ActorRef","description":"发起者","x-source":"CONTRACTS §1","x-mapping":"K"},
      "grantRef": {"$ref":"#/$defs/Id","description":"有效权限子集","x-source":"CONTRACTS §1","x-mapping":"K"},
      "payload": {"$ref":"#/$defs/CommandPayload","description":"封闭类型操作","x-source":"CONTRACTS §1","x-mapping":"K"},
    },
    "required": ["protocol","commandId","sessionId","expectedRevision","actor","grantRef","payload"],
  },
  "CommandPayload": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "kind": {"type":"string","enum":["session.create","graph.patch","node.claim","session.pause","session.resume","session.cancel","effect.reconcile","task.evaluate","candidate.evaluate","asset.promote","asset.activate","asset.revoke","host.observe","effect.receipt","effect.dispatch"],"description":"操作鉴别符","x-source":"CONTRACTS §2","x-mapping":"K"},
      "task": {"anyOf":[{"$ref":"#/$defs/TaskContract"},{"type":"null"}],"description":"session.create 必填","x-source":"CONTRACTS §2","x-mapping":"K"},
      "graph": {"anyOf":[{"$ref":"#/$defs/GraphSpec"},{"type":"null"}],"description":"session.create 必填","x-source":"CONTRACTS §2","x-mapping":"K"},
      "patch": {"anyOf":[{"$ref":"#/$defs/GraphPatch"},{"type":"null"}],"description":"graph.patch 必填","x-source":"CONTRACTS §2","x-mapping":"K"},
      "binding": {"anyOf":[{"$ref":"#/$defs/Binding"},{"type":"null"}],"description":"node.claim/task.evaluate 必填","x-source":"CONTRACTS §2","x-mapping":"K"},
      "objectRef": {"anyOf":[{"$ref":"#/$defs/ArtifactRef"},{"type":"null"}],"description":"effect/host observation/receipt/candidate/asset 的精确输入","x-source":"CONTRACTS §2","x-mapping":"K"},
      "manifestRef": {"anyOf":[{"$ref":"#/$defs/ArtifactRef"},{"type":"null"}],"description":"session.create/resume 必填","x-source":"CONTRACTS §2","x-mapping":"K"},
      "reason": {"anyOf":[{"$ref":"#/$defs/Id"},{"type":"null"}],"description":"cancel/revoke/pause 的理由","x-source":"CONTRACTS §2","x-mapping":"K"},
    },
    "required": ["kind","task","graph","patch","binding","objectRef","manifestRef","reason"],
    "allOf": [{"if":{"properties":{"kind":{"const":"session.create"}}},"then":{"properties":{"task":{"not":{"type":"null"}},"graph":{"not":{"type":"null"}},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"type":"null"},"manifestRef":{"not":{"type":"null"}},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"graph.patch"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"not":{"type":"null"}},"binding":{"type":"null"},"objectRef":{"type":"null"},"manifestRef":{"type":"null"},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"node.claim"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"not":{"type":"null"}},"objectRef":{"type":"null"},"manifestRef":{"type":"null"},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"session.pause"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"type":"null"},"manifestRef":{"type":"null"},"reason":{"not":{"type":"null"}}}}},{"if":{"properties":{"kind":{"const":"session.resume"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"type":"null"},"manifestRef":{"not":{"type":"null"}},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"session.cancel"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"type":"null"},"manifestRef":{"type":"null"},"reason":{"not":{"type":"null"}}}}},{"if":{"properties":{"kind":{"const":"effect.reconcile"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"not":{"type":"null"}},"manifestRef":{"type":"null"},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"task.evaluate"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"not":{"type":"null"}},"objectRef":{"not":{"type":"null"}},"manifestRef":{"type":"null"},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"candidate.evaluate"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"not":{"type":"null"}},"manifestRef":{"type":"null"},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"asset.promote"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"not":{"type":"null"}},"manifestRef":{"type":"null"},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"asset.activate"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"not":{"type":"null"}},"manifestRef":{"type":"null"},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"asset.revoke"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"not":{"type":"null"}},"manifestRef":{"type":"null"},"reason":{"not":{"type":"null"}}}}},{"if":{"properties":{"kind":{"const":"host.observe"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"not":{"type":"null"}},"manifestRef":{"type":"null"},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"effect.receipt"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"not":{"type":"null"}},"manifestRef":{"type":"null"},"reason":{"type":"null"}}}},{"if":{"properties":{"kind":{"const":"effect.dispatch"}}},"then":{"properties":{"task":{"type":"null"},"graph":{"type":"null"},"patch":{"type":"null"},"binding":{"type":"null"},"objectRef":{"not":{"type":"null"}},"manifestRef":{"type":"null"},"reason":{"type":"null"}}}}],
  },
  "CommandResult": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "commandId": {"$ref":"#/$defs/Id","description":"原命令身份","x-source":"CONTRACTS §2","x-mapping":"K"},
      "disposition": {"enum":["committed","duplicate","rejected","archived"],"description":"原子提交/同内容去重/拒绝/迟到归档","x-source":"CONTRACTS §2","x-mapping":"K"},
      "sessionId": {"$ref":"#/$defs/Id","description":"内核会话","x-source":"CONTRACTS §2","x-mapping":"K"},
      "revision": {"$ref":"#/$defs/Count","description":"当前 journal revision","x-source":"CONTRACTS §2","x-mapping":"K"},
      "eventIds": {"type":"array","items":{"$ref":"#/$defs/Id"},"uniqueItems":true,"description":"该事务事件身份","x-source":"CONTRACTS §2","x-mapping":"K"},
      "effectIds": {"type":"array","items":{"$ref":"#/$defs/Id"},"uniqueItems":true,"description":"已提交 outbox intention；未提交不得派发","x-source":"CONTRACTS §2","x-mapping":"K"},
      "decisionRef": {"anyOf":[{"$ref":"#/$defs/ArtifactRef"},{"type":"null"}],"description":"四类裁决工件引用","x-source":"CONTRACTS §2","x-mapping":"K"},
      "error": {"anyOf":[{"$ref":"#/$defs/ErrorEnvelope"},{"type":"null"}],"description":"typed failure，禁止任意异常序列化","x-source":"CONTRACTS §2","x-mapping":"K"},
    },
    "required": ["commandId","disposition","sessionId","revision","eventIds","effectIds","decisionRef","error"],
  },
  "Event": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "protocol": {"$ref":"#/$defs/ProtocolVersion","description":"封套","x-source":"CONTRACTS §1","x-mapping":"K"},
      "eventId": {"$ref":"#/$defs/Id","description":"稳定幂等身份","x-source":"CONTRACTS §1","x-mapping":"K"},
      "sequence": {"type":"integer","minimum":0,"maximum":9007199254740991,"description":"journal 连续序列；不得拿 host seq 直接当 journal seq","x-source":"CONTRACTS §1","x-mapping":"ORDER"},
      "sessionId": {"$ref":"#/$defs/Id","description":"kernel session","x-source":"CONTRACTS §1","x-mapping":"SESSION"},
      "revision": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"journal 事务 revision","x-source":"CONTRACTS §1","x-mapping":"K"},
      "epoch": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"session epoch","x-source":"CONTRACTS §1","x-mapping":"K"},
      "causedBy": {"$ref":"#/$defs/Id","description":"command/effect/receipt identity","x-source":"CONTRACTS §1","x-mapping":"K"},
      "type": {"type":"string","enum":["graph.accepted","graph.patched","node.transition","effect.intended","effect.dispatched","receipt.archived","receipt.applied","decision.recorded","session.epoch-changed","grant.revoked","budget.changed","asset.transition","host.observed","session.paused","session.resumed","session.cancel-requested","session.cancel-confirmed"],"description":"封闭事件目录","x-source":"CONTRACTS §1","x-mapping":"K"},
      "payload": {"$ref":"#/$defs/EventPayload","description":"typed transition/ref payload","x-source":"CONTRACTS §1","x-mapping":"K"},
      "visibility": {"$ref":"#/$defs/Visibility","description":"不可越权回传","x-source":"CONTRACTS §1","x-mapping":"K"},
    },
    "required": ["protocol","eventId","sequence","sessionId","revision","epoch","causedBy","type","payload","visibility"],
  },
  "EventPayload": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "binding": {"anyOf":[{"$ref":"#/$defs/Binding"},{"type":"null"}],"description":"节点/effect 绑定","x-source":"CONTRACTS §1/§5","x-mapping":"K"},
      "objectRef": {"anyOf":[{"$ref":"#/$defs/ArtifactRef"},{"type":"null"}],"description":"不可变对象/receipt 内容引用","x-source":"CONTRACTS §1/§5","x-mapping":"K"},
      "before": {"anyOf":[{"$ref":"#/$defs/NodeState"},{"type":"null"}],"description":"仅 node.transition 使用；其余事件必须 null（session.epoch-changed 的新 epoch 由 Event.epoch 承载）","x-source":"CONTRACTS §1/§5","x-mapping":"K"},
      "after": {"anyOf":[{"$ref":"#/$defs/NodeState"},{"type":"null"}],"description":"仅 node.transition 使用；其余事件必须 null","x-source":"CONTRACTS §1/§5","x-mapping":"K"},
      "effectId": {"anyOf":[{"$ref":"#/$defs/Id"},{"type":"null"}],"description":"effect/receipt 事件必填","x-source":"CONTRACTS §1/§5","x-mapping":"K"},
      "decisionId": {"anyOf":[{"$ref":"#/$defs/Id"},{"type":"null"}],"description":"decision.recorded 必填","x-source":"CONTRACTS §1/§5","x-mapping":"K"},
      "changedIds": {"type":"array","items":{"$ref":"#/$defs/Id"},"minItems":0,"uniqueItems":true,"description":"受影响对象 id","x-source":"CONTRACTS §1/§5","x-mapping":"K"},
      "error": {"anyOf":[{"$ref":"#/$defs/ErrorEnvelope"},{"type":"null"}],"description":"错误原因；不放任意异常对象","x-source":"CONTRACTS §1/§5","x-mapping":"K"},
    },
    "required": ["binding","objectRef","before","after","effectId","decisionId","changedIds","error"],
  },
  "Effect": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "protocol": {"$ref":"#/$defs/ProtocolVersion","description":"封套","x-source":"CONTRACTS §1","x-mapping":"K"},
      "effectId": {"$ref":"#/$defs/Id","description":"持久 intention id","x-source":"CONTRACTS §1","x-mapping":"K"},
      "idempotencyKey": {"$ref":"#/$defs/Id","description":"同一确认未执行重发用同 key","x-source":"CONTRACTS §1","x-mapping":"K"},
      "binding": {"$ref":"#/$defs/Binding","description":"含 epoch/node/attempt/base","x-source":"CONTRACTS §1","x-mapping":"K"},
      "authorityRef": {"$ref":"#/$defs/Id","description":"有效 scoped grant","x-source":"CONTRACTS §1","x-mapping":"K"},
      "reservationRef": {"anyOf":[{"$ref":"#/$defs/Id"},{"type":"null"}],"description":"模型/计费动作必须预算预留","x-source":"CONTRACTS §1","x-mapping":"K"},
      "leases": {"type":"array","items":{"$ref":"#/$defs/LeaseRef"},"minItems":0,"uniqueItems":true,"description":"排他写与 activation 必须有 lease","x-source":"CONTRACTS §1","x-mapping":"K"},
      "inputRefs": {"type":"array","items":{"$ref":"#/$defs/ArtifactRef"},"minItems":0,"uniqueItems":true,"description":"精确输入","x-source":"CONTRACTS §1","x-mapping":"K"},
      "deadline": {"$ref":"#/$defs/Instant","description":"派发期限，注入 Clock","x-source":"CONTRACTS §1","x-mapping":"K"},
      "kind": {"type":"string","enum":["host.agent","host.tool","host.delegate","host.cancel","host.activate","host.reconcile","timer.wait"],"description":"宿主/基础设施执行目录","x-source":"CONTRACTS §1","x-mapping":"K"},
      "payload": {"$ref":"#/$defs/EffectPayload","description":"操作要求，实际动作只能由注入 port","x-source":"CONTRACTS §1","x-mapping":"K"},
    },
    "required": ["protocol","effectId","idempotencyKey","binding","authorityRef","reservationRef","leases","inputRefs","deadline","kind","payload"],
  },
  "EffectPayload": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "context": {"anyOf":[{"$ref":"#/$defs/ContextPlan"},{"type":"null"}],"description":"agent/delegate 上下文","x-source":"CONTRACTS §1/§2","x-mapping":"K"},
      "toolName": {"anyOf":[{"$ref":"#/$defs/Id"},{"type":"null"}],"description":"tool 类型必须非 null","x-source":"CONTRACTS §1/§2","x-mapping":"TOOL"},
      "argumentsRef": {"anyOf":[{"$ref":"#/$defs/ArtifactRef"},{"type":"null"}],"description":"tool 参数工件引用","x-source":"CONTRACTS §1/§2","x-mapping":"K"},
      "graphRef": {"anyOf":[{"$ref":"#/$defs/GraphRef"},{"type":"null"}],"description":"delegate 类型子图","x-source":"CONTRACTS §1/§2","x-mapping":"K"},
      "targetIds": {"type":"array","items":{"$ref":"#/$defs/Id"},"minItems":0,"uniqueItems":true,"description":"cancel/reconcile 涉及的真实会话/effect 集合","x-source":"CONTRACTS §1/§2","x-mapping":"CANCEL"},
      "assetRef": {"anyOf":[{"$ref":"#/$defs/AssetRef"},{"type":"null"}],"description":"activate 精确资产","x-source":"CONTRACTS §1/§2","x-mapping":"K"},
      "previousSnapshot": {"anyOf":[{"$ref":"#/$defs/ArtifactRef"},{"type":"null"}],"description":"activate 必填，失败保留","x-source":"CONTRACTS §1/§2","x-mapping":"K"},
      "deliveryGuarantee": {"type":"string","enum":["none","acknowledged-durable"],"description":"可靠发送不能用 enqueue 代替","x-source":"CONTRACTS §1/§2","x-mapping":"DELIVERY"},
    },
    "required": ["context","toolName","argumentsRef","graphRef","targetIds","assetRef","previousSnapshot","deliveryGuarantee"],
  },
  "LeaseRef": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "resourceId": {"$ref":"#/$defs/Id","description":"排他/共享命名资源","x-source":"CONTRACTS §5; graph SEMANTICS §2.3","x-mapping":"LEASE"},
      "ownerClaimId": {"$ref":"#/$defs/Id","description":"唯一当前 claim","x-source":"CONTRACTS §5; graph SEMANTICS §2.3","x-mapping":"LEASE"},
      "epoch": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"获授 session epoch","x-source":"CONTRACTS §5; graph SEMANTICS §2.3","x-mapping":"LEASE"},
      "fencingToken": {"type":"integer","minimum":1,"maximum":9007199254740991,"description":"单调 token，与 revision/attempt 分开","x-source":"CONTRACTS §5; graph SEMANTICS §2.3","x-mapping":"LEASE"},
      "expiresAt": {"$ref":"#/$defs/Instant","description":"租约 expiry","x-source":"CONTRACTS §5; graph SEMANTICS §2.3","x-mapping":"LEASE"},
    },
    "required": ["resourceId","ownerClaimId","epoch","fencingToken","expiresAt"],
  },
  "Receipt": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "protocol": {"$ref":"#/$defs/ProtocolVersion","description":"封套","x-source":"CONTRACTS §1","x-mapping":"K"},
      "receiptId": {"$ref":"#/$defs/Id","description":"幂等回执","x-source":"CONTRACTS §1","x-mapping":"K"},
      "effectId": {"$ref":"#/$defs/Id","description":"持久 intention 关联","x-source":"CONTRACTS §1","x-mapping":"K"},
      "hostInvocationId": {"anyOf":[{"$ref":"#/$defs/Id"},{"type":"null"}],"description":"原生调用身份；无法关联则 unknown","x-source":"CONTRACTS §1","x-mapping":"INVOCATION"},
      "binding": {"$ref":"#/$defs/Binding","description":"原始 epoch/attempt 绑定不改写","x-source":"CONTRACTS §1","x-mapping":"K"},
      "status": {"type":"string","enum":["completed","failed","cancelled","unknown","not-executed"],"description":"actual outcome，不以模型自述替代","x-source":"CONTRACTS §1","x-mapping":"ACTUAL"},
      "artifactRefs": {"type":"array","items":{"$ref":"#/$defs/ArtifactRef"},"minItems":0,"uniqueItems":true,"description":"真实输出引用","x-source":"CONTRACTS §1","x-mapping":"K"},
      "usage": {"type":"array","items":{"$ref":"#/$defs/Usage"},"minItems":0,"uniqueItems":true,"description":"空列表不代表免费；模型动作无记录即 incomplete","x-source":"CONTRACTS §1","x-mapping":"K"},
      "observability": {"type":"array","items":{"$ref":"#/$defs/Id"},"minItems":0,"uniqueItems":true,"description":"可证明的执行/取消/送达范围","x-source":"CONTRACTS §1","x-mapping":"ACTUAL"},
      "error": {"anyOf":[{"$ref":"#/$defs/ErrorEnvelope"},{"type":"null"}],"description":"固定错误 envelope","x-source":"CONTRACTS §1","x-mapping":"K"},
    },
    "required": ["protocol","receiptId","effectId","hostInvocationId","binding","status","artifactRefs","usage","observability","error"],
  },
  "Usage": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "requestId": {"$ref":"#/$defs/Id","description":"一次请求身份；同请求只结算一次","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"USAGE"},
      "source": {"type":"string","enum":["synthetic","provider","host-normalized","estimate","unknown"],"description":"证据来源，禁止 synthetic 充当 provider","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"USAGE"},
      "inputUncached": {"anyOf":[{"$ref":"#/$defs/Count"},{"type":"null"}],"description":"未缓存输入 token","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"USAGE"},
      "cacheRead": {"anyOf":[{"$ref":"#/$defs/Count"},{"type":"null"}],"description":"缓存读取输入 token","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"USAGE"},
      "cacheWrite": {"anyOf":[{"$ref":"#/$defs/Count"},{"type":"null"}],"description":"单独缓存写入 token，未知为 null","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"USAGE"},
      "output": {"anyOf":[{"$ref":"#/$defs/Count"},{"type":"null"}],"description":"总输出，已包含 reasoning","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"USAGE"},
      "reasoning": {"anyOf":[{"$ref":"#/$defs/Count"},{"type":"null"}],"description":"output 的子集，不重复加","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"USAGE"},
      "total": {"anyOf":[{"$ref":"#/$defs/Count"},{"type":"null"}],"description":"按来源定义规范化总量","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"USAGE"},
      "estimatedUsdMicros": {"anyOf":[{"$ref":"#/$defs/UsdMicros"},{"type":"null"}],"description":"冻结价格估价，非账单","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"COST"},
      "invoiceUsdMicros": {"anyOf":[{"$ref":"#/$defs/UsdMicros"},{"type":"null"}],"description":"真实账单数值，未查 null","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"INVOICE"},
      "complete": {"type":"boolean","description":"原始 usage 完整且归一化校验通过","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"USAGE"},
      "evidenceRefs": {"type":"array","items":{"$ref":"#/$defs/EvidenceRef"},"minItems":0,"uniqueItems":true,"description":"原始与规范化证据","x-source":"CONTRACTS §1/§5; evaluation PROTOCOL §7","x-mapping":"USAGE"},
    },
    "required": ["requestId","source","inputUncached","cacheRead","cacheWrite","output","reasoning","total","estimatedUsdMicros","invoiceUsdMicros","complete","evidenceRefs"],
  },
  "SessionView": {
    "type": "object",
    "additionalProperties": false,
    properties: {
      "sessionId": {"$ref":"#/$defs/Id","description":"只读内核 session","x-source":"CONTRACTS §2","x-mapping":"K"},
      "revision": {"$ref":"#/$defs/Count","description":"journal revision","x-source":"CONTRACTS §2","x-mapping":"K"},
      "epoch": {"$ref":"#/$defs/PositiveCount","description":"当前 session epoch","x-source":"CONTRACTS §2","x-mapping":"K"},
      "taskRef": {"$ref":"#/$defs/ContractRef","description":"任务绑定","x-source":"CONTRACTS §2","x-mapping":"K"},
      "graphRef": {"$ref":"#/$defs/GraphRef","description":"图绑定","x-source":"CONTRACTS §2","x-mapping":"K"},
      "manifestRef": {"$ref":"#/$defs/ArtifactRef","description":"准入 snapshot","x-source":"CONTRACTS §2","x-mapping":"K"},
      "nodeBindings": {"type":"array","items":{"$ref":"#/$defs/Binding"},"uniqueItems":true,"description":"各 attempt 身份，不暗示完成","x-source":"CONTRACTS §2","x-mapping":"K"},
      "nodeStates": {"type":"array","items":{"$ref":"#/$defs/NodeStateEntry"},"uniqueItems":true,"description":"journal 派生的节点状态投影；不暗示完成","x-source":"CONTRACTS §4; graph SEMANTICS §2.2","x-mapping":"K"},
      "unknownEffectIds": {"type":"array","items":{"$ref":"#/$defs/Id"},"uniqueItems":true,"description":"仍需核实的外部效果","x-source":"CONTRACTS §2","x-mapping":"K"},
      "lastSequence": {"anyOf":[{"$ref":"#/$defs/Count"},{"type":"null"}],"description":"空 journal 为 null","x-source":"CONTRACTS §2","x-mapping":"K"},
      "dispatchMode": {"type":"string","enum":["active","paused","cancelling","cancelled"],"description":"仅session派发模式；paused不表示child已停，unknown见unknownEffectIds","x-source":"CONTRACTS §2/§4; 冻结提案","x-mapping":"K"},
    },
    "required": ["sessionId","revision","epoch","taskRef","graphRef","manifestRef","nodeBindings","nodeStates","unknownEffectIds","lastSequence","dispatchMode"],
  },
} as const satisfies DefsSchema;
