// Replace production code only in the module loader's process memory. No frozen file is edited.
export const mutations = [
  { id: 'host-skips-evaluator', file: 'dist/runtime/session/receipts.js', testFile: 'test/l2-kernel-verify-normal.test.js',
    pattern: 'ordinary atomic intention', edits: [["move('verifying');", "move('succeeded');", 2]],
    purpose: 'Host completion may not bypass registered evaluation.' },
  { id: 'missing-intention', file: 'dist/runtime/session/plans.js', testFile: 'test/l2-kernel-verify-normal.test.js',
    pattern: 'ordinary atomic intention', edits: [["effects.push(effect);", "/* mutation: omit outbox effect */", 1]],
    purpose: 'A journal intention without committed effect bytes cannot reach the host.' },
  { id: 'unknown-resend', file: 'dist/kernel/store/outbox.js', testFile: 'test/l2-kernel-verify-faults.test.js',
    pattern: 'crash after native execution', edits: [["entry.state === 'intended').map", "entry.state !== 'resolved').map", 1]],
    purpose: 'Claimed unknown effects stay out of the dispatcher sendable set.' },
  { id: 'incomplete-becomes-zero', file: 'dist/runtime/session/project.js', testFile: 'test/l2-kernel-verify-faults.test.js',
    pattern: 'policy rejects oversubscription', edits: [["{ ...normalized.value, digest: usageIdentity(row) }",
      "{ ...normalized.value, micros: 0, complete: true, digest: usageIdentity(row) }", 1]],
    purpose: 'Incomplete telemetry must retain the actual reservation.' },
  { id: 'old-epoch-applied', file: 'dist/runtime/session/receipts.js', testFile: 'test/l2-kernel-verify-faults.test.js',
    pattern: 'old epoch webhook', edits: [["receipt.binding.epoch !== state.epoch ||", "false ||", 1]],
    purpose: 'Late old-epoch receipts remain archived with unchanged state and budget.' },
  { id: 'budget-policy-bypass', file: 'dist/kernel/policy/risk.js', testFile: 'test/l2-kernel-verify-faults.test.js',
    pattern: 'policy rejects oversubscription', edits: [["if (input.budget.error !== null)", "if (false)", 1],
      ["if (input.budget.snapshot.exhausted)", "if (false)", 1]],
    purpose: 'Runtime scheduling really calls the production policy budget gate.' },
  { id: 'graph-completion-shadow', file: 'dist/kernel/graph/decide.js', testFile: 'test/l2-kernel-verify-normal.test.js',
    pattern: 'ordinary atomic intention', edits: [["return 'succeeded';", "return 'failed';", 1]],
    purpose: 'The application consumes graph.decide outcome, not an independent success branch.' },
];
