/** Complete 0.4.2 manifest/config groups. Each key has a matching README checklist row. */
export const BREAKING_CHANGES = [
  ['cli:init', 'explicit new TaskContract/session bootstrap; legacy scaffolding stays with the old CLI'],
  ['cli:run', 'KernelService.createSession + handleCommand + dispatchEffect; DSH/Pi execute'],
  ['cli:proposal inspect', 'historical source only; new candidates require fresh bound artifacts'],
  ['cli:evidence run', 'EvaluatorPort.evaluateTask with TaskEvidenceReport; do not replay old shell strings'],
  ['cli:gate', 'four independent DecisionRecord kinds, not a legacy gate result'],
  ['cli:ledger show', 'readHistoricalImport for old records; KernelService.readSession for new state'],
  ['cli:ledger verify', 'old CLI/offline verifier only; this exporter does not recompute chains'],
  ['cli:ledger recent', 'historical source only; new journal views use session identity'],
  ['cli:ledger export', 'exportLegacy for a settled copy; importLegacy is an explicit separate action'],
  ['cli:diff', 'old CLI for old generation refs; new WorkspacePort artifacts pin attempt/base'],
  ['cli:rollback', 'old CLI for old refs; new revocation and scoped activation require receipts'],
  ['cli:experiment run', 'new evaluation protocol and matched-budget experiment; rebuild manually'],
  ['cli:experiment export', 'legacy bundle source only; never an EvaluationReceipt'],
  ['cli:report', 'old text/JSON/SARIF/JUnit remain old views; new session/decision views are separate'],
  ['cli:budget', 'historical estimates only; new BudgetPolicy reserves and settles with complete usage'],
  ['cli:status', 'old state overview; new KernelService.readSession is the journal projection'],
  ['cli:doctor', 'old --fix only with the old CLI; no remediation or discovery in this lane'],
  ['cli:flags', 'no flag forwarding; --json/--format/--bundle/--fix and budget/isolation flags remain old CLI contracts'],
  ['contract:contract_version', 'YAML 1 is not runtime 1; explicitly construct runtime/1 schemaVersion 1.1.0'],
  ['contract:objective', 'rebuild TaskContract.goal + acceptance; old score is not uplift evidence'],
  ['contract:hard_invariants', 'rebuild acceptance.checkRefs; do not execute imported commands'],
  ['contract:allowed_evolution_surface', 'rebuild Grant.scope and declared workspace resources'],
  ['contract:protected_paths', 'rebuild scoped permissions and WorkspacePort checks'],
  ['contract:evidence', 'rebuild evaluator checks; the two old defaults remain historical values'],
  ['contract:acceptance', 'rebuild acceptance policy; require_proposal/require_claims grant no qualification'],
  ['contract:capabilities', 'rebuild grants/guarantee requirements; validated authority_ceiling and request-path flags do not prove isolation'],
  ['contract:budgets', 'rebuild shared BudgetPolicy/reservations; iterations and estimates are not new usage receipts'],
  ['config:version', 'YAML 1 stays historical; no default or automatic runtime conversion'],
  ['config:adapters', 'explicit injected HostPort + exact HostManifest; command/model/agent strings do not select or launch a host'],
  ['holdout:regressions', 'historical private source; rebuild evaluator-only checks without revealing oracle feedback'],
  ['experiment:goal_file', 'read source manually and author a new TaskContract'],
  ['experiment:adapter', 'explicit HostPort/HostManifest; no automatic command discovery'],
  ['experiment:iterations', 'new termination.maxAttempts and bounded graph loops'],
  ['experiment:max_wall_clock_ms', 'new budget/termination wall bound; human wait accounted separately'],
  ['experiment:allow_unisolated_agent', 'new Scope.trustDomain and negotiated guarantees; flag grants no sandbox'],
  ['experiment:allow_readable_holdout', 'new evaluator-only privacy policy; old flag grants no new authority'],
  ['ledger:schema_version', 'SQLite marker 2/bundle marker 1 are legacy only; unmarked v1/unknown versions refused'],
  ['ledger:events', 'historical records only; no Event/Receipt/TaskEvidenceReport creation'],
  ['ledger:generations', 'historical Git references only; not AssetRef or activation qualification'],
  ['ledger:state', 'historical schema_version/active_generation; never a runtime projection'],
  ['ledger:chain', 'copy payload_json/previous_hash/event_hash byte-for-byte; never migrate or recompute'],
  ['ledger:integrity', 'copy declared bundle integrity; structural checks do not prove cryptographic authenticity'],
] as const;
