import { MAPPINGS } from './mapping.js';
import type { DeliverySnapshot, LossEntry } from './types.js';

export function mappingReport(): readonly LossEntry[] { return MAPPINGS.map(row => ({ ...row })); }
export function lossesFor(delivery: DeliverySnapshot): readonly LossEntry[] {
  const sources = new Set<string>();
  for (const node of delivery.nodes) {
    sources.add(`${node.type}.status.${node.status}`);
    if (Object.hasOwn(node, 'review')) sources.add('node.review');
    if (Object.hasOwn(node, 'assigned_to')) sources.add('node.assigned_to');
  }
  for (const edge of delivery.edges) sources.add('edge.type.' + edge.type);
  if (Object.hasOwn(delivery.graph, 'review')) {
    sources.add('graph.review.status'); sources.add('graph.review.by'); sources.add('graph.review.at');
    const review = delivery.graph.review as { layers?: unknown[] };
    if (review.layers !== undefined && review.layers.length > 0) {
      for (const key of ['level', 'by', 'at']) sources.add('graph.review.layers.' + key);
    }
  }
  if (Object.hasOwn(delivery.graph, 'design_approved')) sources.add('graph.design_approved');
  return MAPPINGS.filter(row => row.classification !== 'supported' && sources.has(row.source)).map(row => ({ ...row }));
}
export interface Difference { readonly path: string; readonly before: unknown; readonly after: unknown }
/** Compare value/presence, array ordering and every field; object key order is immaterial. */
export function difference(before: unknown, after: unknown, at = '$'): readonly Difference[] {
  if (Object.is(before, after)) return [];
  if (typeof before === 'object' && before !== null && typeof after === 'object' && after !== null && Array.isArray(before) === Array.isArray(after)) {
    const a = before as Record<string, unknown>, b = after as Record<string, unknown>;
    const keys = [...new Set([...Object.keys(a), ...Object.keys(b)])].sort();
    const result: Difference[] = [];
    for (const key of keys) {
      if (!Object.hasOwn(a, key) || !Object.hasOwn(b, key)) result.push({ path: at + '.' + key, before: a[key], after: b[key] });
      else result.push(...difference(a[key], b[key], at + '.' + key));
    }
    if (Array.isArray(before) && Array.isArray(after) && before.length !== after.length && result.length === 0) {
      result.push({ path: at + '.length', before: before.length, after: after.length });
    }
    return result;
  }
  return [{ path: at, before, after }];
}
/** The tracked product loss report is generated from the same executable mapping table. */
export function renderLossReport(): string {
  const escape = (value: string) => value.replace(/\|/g, '\\|').replace(/\r\n?/g, '\n').replace(/\n/g, '<br>');
  return [
    '# SP bridge semantic mapping and loss report', '',
    'Generated by `renderLossReport()`; do not hand-copy mapping rows.', '',
    'Scope: explicitly assembled `evofence.sp-snapshot/1` YAML/JSON fixtures, not native SP directory discovery or every `graph export` format.',
    'Delivery graph and runtime graph are distinct. Imports are historical-delivery data with executable=false.',
    'Only task/context/ADR records, artifact path annotations and text contracts are converted. Artifact bytes are never read or qualified.',
    'iterates stays documentary; fallback requires explicit runtime bounds/predicate and does not order; review never grants authority.', '',
    'Evidence: native-fixture. Native multi-graph SP exports, provider-live behavior and OS/host activation remain unknown.',
    'Controlled capability uplift: inconclusive; l4_capability_trial attempt 1 failed; 747 / 943 USD remain unresolved; preregistered envelope 938.470100 USD.',
    'adr_0001 / adr_0004 remain proposed; dual-host-runtime-and-uplift has not graduated.', '',
    '| SP source | Target | Classification | Reason |', '| --- | --- | --- | --- |',
    ...mappingReport().map(row => `| ${escape(row.source)} | ${escape(row.target)} | ${row.classification} | ${escape(row.reason)} |`), '',
  ].join('\n');
}
